### ISSUE TITLE
Help Menu missing a referenced CLI command

### ISSUE THREAD

**Issue by MardukNT** [RichardMidnight/pi-safe#11]
Hello RichardMidnight,
When checking the Help Menu, I noticed a CLI function is referenced, but the command itself is absent. (see screenshot).

![Help-GUI](https://user-images.githubusercontent.com/79539480/111884291-f177a700-897d-11eb-96db-2f1c0a66e2de.png)

**Comment by RichardMidnight** [comment]
MardukNT,
Thank you for the feedback.  Typing pisafe without any other arguments brings up the menu.  This is by design, but I was not exactly sure how to note that in the help.  Should I put  < leave blank > ?

**Comment by MardukNT** [comment]
RichardMidnight,
Good question.  Might I suggest the following wording:

pisafe    - pisafe <'with no additional arguments'> launches the PiSafe GUI (recommended)

Or something to that effect.
--Cheers
