### ISSUE TITLE
[Feature Request] Export log file with the creation of backup image

### ISSUE THREAD

**Issue by MardukNT** [RichardMidnight/pi-safe#12]
Hello RichardMidnight,
Would it be possible to include a choice that would allow the log file to be written to the same directory the backup image is created in?
Either as a variable/condition to set in the PiSafe config file and/or via a CLI function?

That logging option should allow me to better track PiSafe's speed/performance over time.

**Comment by RichardMidnight** [comment]
MardukNT, Thanks for the good suggestion.  I have just added to ver 1.1 (which is not out yet) the ability to set the log file location by editing the config file.  It is called 'log_file='.
Peace, RichardMidnight.
