### ISSUE TITLE
Does this bash support backup raspberry system which boot from hdd or usb ？

### ISSUE THREAD

**Issue by GoogleBeEvil** [RichardMidnight/pi-safe#21]
most of backup script only support SD card boot system，can not run script on usb-boot sysytem，does this support that？

**Comment by RichardMidnight** [comment]
Yes it does with hardware that supports USB boot like a pi-4.   I don't think anything before a pi-4 will USB boot, and some pi-4s need a firmware update to support USB boot.  You can even create an image file from an SD card and restore it to a usb stick.
