### ISSUE TITLE
[Question]Is there any possiable to backup without a second SD/USB/HDD?

### ISSUE THREAD

**Issue by GoogleBeEvil** [RichardMidnight/pi-safe#23]
Can this script add feature “pre-allocated an *.image which the size is 300MB(optioned) biger than the used space ”,  and rsync the files to the blank  image(exclude the image path),this will allow backup with only one SD card , because pre-allocate image size is auttually 'pre -pishrinked' and  can locate in the free space .there were used to be another script using this method ,but it seems the author wont maintain it anymore,it abit buggy for only support sd card boot(released before raspi support usb boot)
https://github.com/nanhantianyi/rpi-backup/blob/master/back.sh

**Comment by RichardMidnight** [comment]
Hello GoogleBeEvil,

If I understand what you are asking, that is out of the scope of PiSafe.  PiSafe is designed to create a small image file of a linux media device (like an sd card or a usb stick).  It is a byte-by-byte-copy not a file-copy and needs to be stored on a separate device during the image file creation process.  The second device can be pretty much any storage media available including a network share.  I hope this is useful.
