### ISSUE TITLE
cron job issue when new version checking

### ISSUE THREAD

**Issue by DmytroKorniienko** [RichardMidnight/pi-safe#26]
Hi again. I found one more issue.

I use pi-safe as cron task and rexpect unattending work, but today I found 100% busy pisafe task which was had run two days ago. I killed it and backup process continue and completed sucessfully. After my manual execution of pisafe I see:

```
pisafe
PiSafe: UPDATE AVAILABLE: Update PiSafe from '1.2.2' to '1.2.3' [y/n]?Updating PiSafe to v 1.2.3...
1.2.3 installed. Press any key to exit...
```

Can you not lock work with a wait of response please when script running with a parameters? I will be appreciated you a lot.

**Comment by RichardMidnight** [comment]
[DmytroKorniienko](https://github.com/DmytroKorniienko),
I will look into this. For now, I think you can turn off "check_for_updates_on_startup".
type in "pisafe settings"    (or "pisafe config" in older versions)
then change check_for_updates_on_startup=off
you should check for updates on a regular basis as I have been improving pisafe
- peace

**Comment by DmytroKorniienko** [comment]
Thank you!
