### ISSUE TITLE
Ignore specific partitions?

### ISSUE THREAD

**Issue by rebirth90** [RichardMidnight/pi-safe#31]
Hello dear developer!
i have a weird situation where i'm using a single hdd with 3 partitions (boot, OS, share). Is there any way to ignore the share partition and backup the boot + OS?
dev/sda with sda1 (boot), sda2 (OS), sda3 (share)

**Comment by RichardMidnight** [comment]
Hello rebirth90,
Unfortunately PiSafe cannot ignore specific partitions.  That is a more in-depth operation than PiSafe is designed to do.  It would not be too hard to ignore the last partition, but the partition table will still be looking for it and give an error and probably be unstable.

Note: There is an option to "ignore freespace_at_end".  So if you backup your share partition and delete it with gparted or something (this is risky!!), or move it to a different device, PiSafe will create an image of the boot and OS partitions and ignore the freespace at the end of the drive where the share was.

I hope PiSafe is useful to you.

Peace,

Richard
