### ISSUE TITLE
SD card >16Gb: nothings happens after warning. No backup

### ISSUE THREAD

**Issue by ottodijk** [RichardMidnight/pi-safe#36]
I use a sd card 64Gb. pisave 1.2.9. Warning "57.9 > 16Gb, beter use 16Gb ore less, with ok selected and then enter. 
Warning stays on. Nothing happens thereafter.
P400 with 4Gb nenory, bulseye 64
Try Start pisafe in terminal AND Menu

**Comment by RichardMidnight** [comment]
I will investigate.  Are you backing up a 64GB SD card?  Is there more than 128GB available on your destination drive?

**Comment by RichardMidnight** [comment]
It is working for me.  64GB card going to a 128GB location which has 84GB available.
You do have to tab over to the OK button and press Enter when you get the warning.

**Comment by ottodijk** [comment]
I am a new to this. Didn't use tab. Now it is working.
GREAT WORK
thank you very much
