### ISSUE TITLE
Virtualbox on Windows-sdcard not found

### ISSUE THREAD

**Issue by xsleepejelly** [RichardMidnight/pi-safe#39]
Hello,
I've been trying to get my windows virtualbox to find recognize my usb sdcard reader with no luck.  It was mentioned in the active issue that you were able to run it in Windows without an issue.  The option to attach the usb does not come up and trying to create a vmdk file keeps giving me an error.  Do you remember doing anything to get windows to recognize the usb sd card reader?

**Comment by RichardMidnight** [comment]
Hello xsleepejelly,

I just saw this message.  

I have not run it in a few months, but I have had good success running linux on a windows computer using virtual box and using USB devices.  The trick I found is you have to tell windows to pass the usb port (SD card) through to linux.  I usually did this with the little USB icon in the bottom right hand corner of the virtual box window.  There are probably other ways to do that.
