### ISSUE TITLE
Install mousepad or allow to configure the editor used by pi-safe.

### ISSUE THREAD

**Issue by cClaude** [RichardMidnight/pi-safe#4]
** mousepad ** is required, it must be installed with the other packages.

```
pisafe: line 1430: mousepad: command not found
```

An alternative is to allow to configure the editor used by pi-safe.

Thank you

**Comment by RichardMidnight** [comment]
Thanks.  The alpha version (not yet released) now sets the editor to nano if mousepad is not found.  Also, you can set your preferred text editor.

**Comment by RichardMidnight** [comment]
current version sets the editor to nano if mousepad is not found. Also, you can set your preferred text editor.

**Comment by RichardMidnight** [comment]
New version 0.9.18 should address this.
Thanks for letting me know.

**Comment by cClaude** [comment]
I confirm that working as expected now.
