### ISSUE TITLE
Difficult to distinguish which volume is the source, which the target

### ISSUE THREAD

**Issue by saelkind** [RichardMidnight/pi-safe#40]
I had trouble figuring out which disk was the source, which the target.  Youtube videos of an earlier(?) version showed this explicitly called out in the character-cell UI.  Can you either update the README to point out which is which in the current UI, and/or add it to the UI in the next update?

**Comment by RichardMidnight** [comment]
Hello Saelkind,
Thank you for the feedback.  I am happy to add clarity to either the README or the software itself, but I do not understand what to change.  Honestly, I am probably too close to the software to see the confusion.  Please help me understand.

1) Pisafe gets installed on a working Linux system.
2) When you run Pisafe, it reads  a "source media" (typically an SD card in a USB reader, often sda), and creates an image file in the downloads folder of the working Linux system (or you can save it almost anywhere other than the source media).

-
