### ISSUE TITLE
Not usefull if your system is on SSD

### ISSUE THREAD

**Issue by Chobberr** [RichardMidnight/pi-safe#42]
I cannot use it due it cannot detect my system on a SSD - so now I want to remove it again. It would be nice for beginners like me if you could mention how to remove it. 

thank you!

Kind regards - Chobberr

**Comment by RichardMidnight** [comment]
The beta version supports NVME SSDs.  See a closed issue.  Currently you need to run the beta with sudo, but I will fix that soon.  If the beta does not work for you, please run "lsblk" and show me the results.

**Comment by RichardMidnight** [comment]
The latest version supports NVME SSDs.  If this does not work for you, please run "lsblk" and show me the results.

Also, there is an uninstall option in the menu and the CLI.
