### ISSUE TITLE
Backup to "external" drive

### ISSUE THREAD

**Issue by htilburgs** [RichardMidnight/pi-safe#45]
I like to make a backup to an Synology Nas, that is mounted on my rpi (/mnt/backup).
Is that possible with this script?

Currently I use `dd if=/dev/mmcblk0 of=/mnt/backup/$HOSTNAME.$(date +%Y%m%d).img bs=4M`

The problem with this is that it creates a 32Gb file for a 32Gb SD card and I like to be it smaller.

**Comment by RichardMidnight** [comment]
Probably, but probably needs a few settings.  
- Set default directory to /mnt/backup
- Turn OFF hide-root-device.
