### ISSUE TITLE
Command line options to automate backups

### ISSUE THREAD

**Issue by davidmarshall15** [RichardMidnight/pi-safe#5]
_I run a few pi's 24x7 and have backup solutions in place for databases and such but nothing for the os itself, this seems to be a very good method of backing up the os to an image for fast recovery.

It would be great to use this backup method via the cron using command line parameters, is this something of consideration?_

EDIT: Apologies,  I really should have looked at the code first, watch the video and gained the impression this was only usable via the menu, especially with the additional confirmations and countdown. But I see in the code it expects parameters, maybe just a parameter to turn off the confirmation is all that's needed.

Thanks

**Comment by RichardMidnight** [comment]
PiSafe started with only a command line interface.  Then I added the menu.  I may have broken some of the cli.  I will try to check and fix this weekend.  Help shows usage.  Eg: " pisafe backup sda newimage "
