### ISSUE TITLE
pi-safe help contains spelling errors

### ISSUE THREAD

**Issue by MardukNT** [RichardMidnight/pi-safe#8]
Let me start off by saying I'm enjoying your app!

While reviewing the help section for tips on how to use pi-safe from CLI, and not via the GUI, I noticed there were some spelling errors. See below.

**Corrections listed in-line:**
 PiSafe v0.9.21  - Designed for Raspberry Pi
  - Backup your SD card to an image file
  - Restore your SD card from an image file

 Usage:
   pisafe [function] [device/file] [file/device]

 Function is:
                             - startup the gui menu (this is recomended) **<-- recommended is spelled with two m's**
   list                      - list SD-devices and image-files
   backup [device] [file]    - backup SD-card to image-file
   restore [file] [device]   - restore image-file to SD-card
   install                   - install this script
   update                    - update script from webiste **<-- Should be changed to website _(i and s reversed)_**
   -v                        - display version
   help | -h                 - help

 Notes:
  - Supports .img .zip .xz and .gz files.  Appends '.img.img' if no extension is specified
  - Specifying an '.img' extension is faster, but twice the size because it is not compressed with img.

 Examples:
 pisafe
 pisafe list
 pisafe backup sda newimage
 pisafe backup /dev/sdb newimage.xz
 pisafe restore newimage.img.zip sda

**Note:** This issue doesn't break app functionality, but the spelling errors should be corrected at some point, as it looks bad.

**Comment by RichardMidnight** [comment]
Thank you.  
fixed in 0.9.22
